### ISSUE TITLE
Can't connect to a room to play the game

### ISSUE THREAD

**Issue by bedesv** [d-exclaimation/message-racer#5]
![Screenshot 2023-06-07 at 7 30 24 PM](https://github.com/d-exclaimation/message-racer/assets/5328041/d0c9317f-d230-4ccd-9440-32c2bdbe45ac)

**Comment by d-exclaimation** [comment]
lol, I abandoned this project a while ago and I never got to documenting any of these properly. I no longer have a deployed server for this project anymore. You need to run your own instance of the server. 

Here's the quick run of what is needed to run the server.

1. Probably starts with installing Elixir (https://elixir-lang.org/install.html)
2. You might also need a Postgres database up with name `message_racer_dev`
3. Clone the project, navigate to the server directory and install all deps from mix using 
```sh
mix deps.get
```
4. Migrate the database using
```sh
mix echo.migrate
```
3. Lastly, run to get Phoenix up and running
```sh
mix phx.server
```
